### ISSUE TITLE
doesn't allow for multiple todolist workspaces

### ISSUE THREAD

**Issue by turbo-turnip** [legit-programming/Todo-App#18]
doesn't allow for multiple todolist workspaces, where there are multiple workspaces saved with different todo lists

**Comment by aroary** [comment]
todolist json format should be
```json
{
  "todoLists": [
    "id": 2,
    "tasks": [
      {
        "task": "NAME",
        "description": "DESCRIPTION",
        "priority": 1,
        "done": false,
        "id": 1,
        "createDate": "DATE"
      }
    ],
    "completed": []
  ]
}
```

**Comment by turbo-turnip** [comment]
you should store date as an actual date object in python, and stringify it when writing to the json file

**Comment by aroary** [comment]
> you should store date as an actual date object in python, and stringify it when writing to the json file

a string is easy enough to work with even for the sorting
